### ISSUE TITLE
test2

### ISSUE THREAD

**Issue by anashasan** [farhanmallick/Test#2]

**Comment by farhanmallick** [comment]
The issue has been resolved

     public static List<SelectListItem> PopulateActivateTrader()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            DbConnectionClass db = new DbConnectionClass();
            DataTable dt = db.getSelectDatadt("Select LoginID as TraderID  from traders where UserID = '100060000' and Status_client = 'A'  order by LoginID");


            foreach (DataRow dtRow in dt.Rows)
            {
                items.Add(new SelectListItem
                {
                    Text = dtRow["TraderID"].ToString(),
                    Value = dtRow["TraderID"].ToString()
                });
            }



            return items;
        }
